FROM ghcr.io/cloudnative-pg/postgresql:16.7-bookworm AS build

USER root

RUN apt-get update && \
    apt-get install -y \
    build-essential \
    git \
    postgresql-server-dev-16

RUN git clone https://github.com/sraoss/pg_ivm.git /usr/src/pg_ivm --branch v1.8

WORKDIR /usr/src/pg_ivm

RUN make && make install

FROM ghcr.io/cloudnative-pg/postgresql:16.7-bookworm

USER root

COPY --from=build /usr/lib/postgresql/16/lib/pg_ivm.so /usr/lib/postgresql/16/lib/
COPY --from=build /usr/share/postgresql/16/extension/pg_ivm.control /usr/share/postgresql/16/extension/
COPY --from=build /usr/share/postgresql/16/extension/pg_ivm--*.sql /usr/share/postgresql/16/extension/

USER 26