name: ci

on:
  push:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push 16
        uses: docker/build-push-action@v6
        with:
          file: Dockerfile-16
          push: true
          tags: playmentsadmin/postgres-cloudnative-ivm:16.3

      -
        name: Build and push PG 17
        uses: docker/build-push-action@v6
        with:
          file: Dockerfile-17
          push: true
          tags: playmentsadmin/postgres-cloudnative-ivm:17.0
